In [46]:
import numpy as np
import pandas as pd

In [47]:
data=pd.read_csv('iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [48]:
X=data.drop(['Id','Species'],axis=1)
Y=data['Species']

In [50]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [51]:
cross_val_score(SVC(),X,Y,cv=3)

array([0.96, 0.98, 0.94])

In [52]:
cross_val_score(RandomForestClassifier(n_estimators=50),X,Y,cv=3)

array([0.98, 0.92, 0.96])

In [53]:
cross_val_score(LogisticRegression(random_state=30,max_iter=120),X,Y,cv=3)

array([0.98, 0.96, 0.98])